import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// const kanit = localFont({
//     src: [
//         {
//             path: "./fonts/Kanit-Black.tff",
//             weight: "900",
//             style: "normal",
//         },
//         {
//             path: "./fonts/Kanit-ExtraBold.tff",
//             weight: "800",
//             style: "normal",
//         },
//         {
//             path: "./fonts/Kanit-Bold.tff",
//             weight: "700",
//             style: "normal",
//         },
//         {
//             path: "./fonts/Kanit-SemiBold.tff",
//             weight: "600",
//             style: "normal",
//         },
//         {
//             path: "./fonts/Kanit-Medium.tff",
//             weight: "500",
//             style: "normal",
//         },
//         {
//             path: "./fonts/Kanit-Regular.ttf",
//             weight: "400",
//             style: "normal",
//         },
//         {
//             path: "./fonts/Kanit-Thin.tff",
//             weight: "200",
//             style: "normal",
//         },
//     ],
//     variable: "--font-kanit"
// })

const workSans = localFont({
    src: [
        {
            path: "./fonts/WorkSans-Black.ttf",
            weight: "900",
            style: "normal"
        },
        {
            path: "./fonts/WorkSans-ExtraBold.ttf",
            weight: "800",
            style: "normal"
        },
        {
            path: "./fonts/WorkSans-Bold.ttf",
            weight: "700",
            style: "normal"
        },
        {
            path: "./fonts/WorkSans-SemiBold.ttf",
            weight: "600",
            style: "normal"
        },
        {
            path: "./fonts/WorkSans-Medium.ttf",
            weight: "500",
            style: "normal"
        },
        {
            path: "./fonts/WorkSans-Regular.ttf",
            weight: "400",
            style: "normal"
        },
        {
            path: "./fonts/WorkSans-Thin.ttf",
            weight: "200",
            style: "normal"
        },
        {
            path: "./fonts/WorkSans-ExtraLight.ttf",
            weight: "100",
            style: "normal"
        },
    ],
    variable: "--font-work-sans"
})

export const metadata: Metadata = {
    title: "DevLens | Processing Data",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${workSans.variable}`}
            >
                {children}
            </body>
        </html>
    );
}
